/**
 * Export Service — Phantom Hunter
 * Handles exporting hunt results in JSON, CSV, Markdown, and PDF formats.
 */

// ── JSON Export ───────────────────────────────────────────────────────────────

export function exportHuntsAsJSON(hunts, filename = 'phantom-hunts') {
  const exportData = {
    exportedAt: new Date().toISOString(),
    generator: 'Phantom Hunter v1.0',
    huntCount: hunts.length,
    hunts: hunts.map(h => ({
      id: h.id,
      title: h.title,
      category: h.category,
      severity: h.severity,
      confidence: h.confidence,
      relevanceScore: h.relevanceScore,
      mitreTechniques: h.mitreTechniques,
      hypothesis: h.hypothesis,
      whyRelevant: h.whyRelevant,
      huntSteps: h.huntSteps,
      exampleQueries: h.exampleQueries,
      dataSources: h.dataSources,
      suspiciousBehaviors: h.suspiciousBehaviors,
      truePositiveIndicators: h.truePositiveIndicators,
      falsePositiveIndicators: h.falsePositiveIndicators,
      triageGuidance: h.triageGuidance,
      remediationActions: h.remediationActions,
      tags: h.tags,
      generatedAt: h.generatedAt,
    })),
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `${filename}-${formatDate()}.json`);
  URL.revokeObjectURL(url);
}

// ── Single Hunt JSON ──────────────────────────────────────────────────────────

export function exportSingleHuntJSON(hunt) {
  const blob = new Blob([JSON.stringify(hunt, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `hunt-${hunt.id}-${formatDate()}.json`);
  URL.revokeObjectURL(url);
}

// ── Markdown Export ───────────────────────────────────────────────────────────

export function exportHuntAsMarkdown(hunt) {
  const lines = [
    `# ${hunt.title}`,
    '',
    `**Category:** ${hunt.category}  `,
    `**Severity:** ${hunt.severity}  `,
    `**Confidence:** ${hunt.confidence}%  `,
    `**Estimated Time:** ${hunt.estimatedTime}  `,
    `**Difficulty:** ${hunt.difficulty}  `,
    '',
    '## Why This Hunt is Relevant',
    hunt.whyRelevant || '',
    '',
    '## Threat Hypothesis',
    hunt.hypothesis || '',
    '',
    '## MITRE ATT&CK Techniques',
    (hunt.mitreTechniques || []).map(t => `- \`${t}\``).join('\n'),
    '',
    '## Required Data Sources',
    (hunt.dataSources || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Hunt Procedure',
    (hunt.huntSteps || []).map((s, i) => `${i + 1}. ${s}`).join('\n'),
    '',
    '## Example Queries',
    ...(hunt.exampleQueries || []).flatMap(q => [
      `### ${q.platform}`,
      '```',
      q.query,
      '```',
      '',
    ]),
    '## Suspicious Behaviors to Look For',
    (hunt.suspiciousBehaviors || []).map(s => `- ${s}`).join('\n'),
    '',
    '## True Positive Indicators',
    (hunt.truePositiveIndicators || []).map(s => `- ${s}`).join('\n'),
    '',
    '## False Positive Indicators',
    (hunt.falsePositiveIndicators || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Triage Guidance',
    hunt.triageGuidance || '',
    '',
    '## Escalation Recommendations',
    (hunt.escalationRecommendations || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Remediation Actions',
    (hunt.remediationActions || []).map(s => `- ${s}`).join('\n'),
    '',
    `---`,
    `*Generated by Phantom Hunter on ${new Date(hunt.generatedAt || Date.now()).toLocaleDateString()}*`,
  ];

  const md = lines.join('\n');
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `hunt-${sanitizeFilename(hunt.title)}-${formatDate()}.md`);
  URL.revokeObjectURL(url);
}

// ── Copy to Clipboard ─────────────────────────────────────────────────────────

export async function copyHuntToClipboard(hunt) {
  const text = formatHuntAsText(hunt);
  await navigator.clipboard.writeText(text);
}

export async function copyQueryToClipboard(query) {
  await navigator.clipboard.writeText(query.query);
}

// ── Single Hunt PDF ───────────────────────────────────────────────────────────

export function exportSingleHuntAsPDF(hunt, brandOptions = {}) {
  const html = buildSingleHuntPDF(hunt, brandOptions);
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 600);
  }
}

// ── Multi Hunt PDF ────────────────────────────────────────────────────────────

export function exportHuntsAsPDF(hunts, companyProfile) {
  const html = buildPrintableHTML(hunts, companyProfile);
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 600);
  }
}

// ── CSV Export ─────────────────────────────────────────────────────────────────

export function exportHuntsAsCSV(hunts, filename = 'phantom-hunts') {
  const headers = [
    'ID', 'Title', 'Category', 'Severity', 'Confidence', 'Relevance Score',
    'Difficulty', 'Estimated Time', 'MITRE Techniques', 'Tags',
  ];

  const rows = hunts.map(h => [
    h.id,
    `"${(h.title || '').replace(/"/g, '""')}"`,
    h.category,
    h.severity,
    h.confidence,
    h.relevanceScore,
    h.difficulty,
    h.estimatedTime,
    `"${(h.mitreTechniques || []).join(', ')}"`,
    `"${(h.tags || []).join(', ')}"`,
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `${filename}-${formatDate()}.csv`);
  URL.revokeObjectURL(url);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function triggerDownload(url, filename) {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

function formatDate() {
  return new Date().toISOString().split('T')[0];
}

function sanitizeFilename(str) {
  return (str || 'hunt').replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40);
}

function formatHuntAsText(hunt) {
  return [
    `THREAT HUNT: ${hunt.title}`,
    `${'='.repeat(60)}`,
    '',
    `Category: ${hunt.category} | Severity: ${hunt.severity} | Confidence: ${hunt.confidence}%`,
    '',
    'WHY RELEVANT',
    hunt.whyRelevant,
    '',
    'HYPOTHESIS',
    hunt.hypothesis,
    '',
    'MITRE TECHNIQUES',
    (hunt.mitreTechniques || []).join(', '),
    '',
    'HUNT STEPS',
    (hunt.huntSteps || []).map((s, i) => `${i + 1}. ${s}`).join('\n'),
    '',
    'SUSPICIOUS BEHAVIORS',
    (hunt.suspiciousBehaviors || []).map(s => `• ${s}`).join('\n'),
    '',
    'TRIAGE GUIDANCE',
    hunt.triageGuidance,
  ].join('\n');
}

// ── Severity color helpers ─────────────────────────────────────────────────────

function severityColor(s) {
  return { critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#22c55e' }[s] || '#6b7280';
}

function severityBg(s) {
  return { critical: 'rgba(239,68,68,0.15)', high: 'rgba(249,115,22,0.15)', medium: 'rgba(234,179,8,0.15)', low: 'rgba(34,197,94,0.15)' }[s] || 'rgba(107,114,128,0.15)';
}

// ── Ghost SVG inline (for PDF) ─────────────────────────────────────────────────

const GHOST_SVG = `<svg xmlns="http://www.w3.org/2000/svg" width="48" height="56" viewBox="0 0 48 56" fill="none">
  <defs>
    <radialGradient id="gInner" cx="50%" cy="40%" r="50%">
      <stop offset="0%" stop-color="#2a2a2a"/>
      <stop offset="100%" stop-color="#0a0a0a"/>
    </radialGradient>
    <radialGradient id="gEye" cx="50%" cy="50%" r="50%">
      <stop offset="0%" stop-color="#ff6060"/>
      <stop offset="100%" stop-color="#dc2626"/>
    </radialGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="2" result="blur"/>
      <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>
  <!-- Ghost body -->
  <path d="M4 24 C4 11 13 2 24 2 C35 2 44 11 44 24 L44 54 L37 48 L30 54 L24 48 L18 54 L11 48 L4 54 Z"
    fill="url(#gInner)" stroke="#dc2626" stroke-width="1.5"/>
  <!-- Left eye (with crosshair) -->
  <circle cx="17" cy="24" r="5" fill="url(#gEye)" filter="url(#glow)"/>
  <line x1="12" y1="24" x2="22" y2="24" stroke="#ff6060" stroke-width="0.8" opacity="0.7"/>
  <line x1="17" y1="19" x2="17" y2="29" stroke="#ff6060" stroke-width="0.8" opacity="0.7"/>
  <circle cx="17" cy="24" r="2" fill="#ff2222"/>
  <!-- Right eye -->
  <circle cx="31" cy="24" r="5" fill="url(#gEye)" filter="url(#glow)"/>
  <circle cx="31" cy="24" r="2" fill="#ff2222"/>
</svg>`;

// ── Single Hunt PDF Template ──────────────────────────────────────────────────

function buildSingleHuntPDF(hunt, brandOptions = {}) {
  const primary  = brandOptions.primaryColor || '#dc2626';
  const accent   = brandOptions.accentColor  || '#ef4444';
  const logoUrl  = brandOptions.logoUrl      || '';
  const coName   = brandOptions.companyName  || '';
  const analystName  = brandOptions.analystName    || '';
  const classification = brandOptions.classification || '';
  const reportTitle    = brandOptions.reportTitle   || hunt.title;
  const footerNote     = brandOptions.footerNote    || '';
  const sections  = brandOptions.includeSections || {
    overview: true, huntSteps: true, queries: true,
    iocs: true, remediation: true, notes: true,
  };

  const sev = hunt.severity || 'medium';
  const sevColor = severityColor(sev);
  const sevBg    = severityBg(sev);
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const genDate = hunt.generatedAt ? new Date(hunt.generatedAt).toLocaleDateString() : now;

  const queries = (hunt.exampleQueries || []).map(q => `
    <div class="query-block">
      <div class="query-header">
        <span class="pill pill-blue">${escapeHtml(q.platform || '')}</span>
        <span class="pill pill-purple">${escapeHtml((q.language || 'QUERY').toUpperCase())}</span>
      </div>
      ${q.description ? `<p style="font-size:11.5px;color:#6b7280;margin:4px 0 6px;font-style:italic;">${escapeHtml(q.description)}</p>` : ''}
      <pre class="code">${escapeHtml(q.query || '')}</pre>
    </div>
  `).join('');

  const steps = (hunt.huntSteps || []).map((s, i) => `
    <div class="step">
      <div class="step-num">${i + 1}</div>
      <div class="step-text">${escapeHtml(s)}</div>
    </div>
  `).join('');

  const investigationSteps = (hunt.investigationSteps || []).map((s, i) => `
    <div class="step">
      <div class="step-num" style="background:#fff3e0;border-color:#f97316;color:#ea580c;">${i + 1}</div>
      <div class="step-text">${escapeHtml(s)}</div>
    </div>
  `).join('');

  // MITRE techniques are objects {id, name, tactic} — extract id and name
  const mitre = (hunt.mitreTechniques || []).map(t => {
    const id   = typeof t === 'string' ? t : (t?.id || '');
    const name = typeof t === 'object' ? (t?.name || '') : '';
    return `<span class="mitre-tag">${escapeHtml(id)}${name ? ` — ${escapeHtml(name)}` : ''}</span>`;
  }).join('');

  const listItems = (arr) =>
    (arr || []).map(s => `<li>${escapeHtml(s)}</li>`).join('');

  const actors = (hunt.relevantThreatActors || []).map(a => `
    <div class="actor">
      <div class="actor-dot" style="background:${a.color || '#dc2626'}"></div>
      <div>
        <div class="actor-name">${escapeHtml(a.name)}</div>
        <div class="actor-meta">${escapeHtml(a.nation || '')} — ${escapeHtml(a.riskLevel || '')}</div>
      </div>
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Phantom Hunter — ${escapeHtml(hunt.title)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Segoe UI', Arial, sans-serif;
      background: #ffffff;
      color: #111827;
      font-size: 13px;
      line-height: 1.6;
    }

    @page { size: A4; margin: 0; }

    @media print {
      .no-print { display: none; }
      .cover, .metrics { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }

    /* ── Layout ── */
    .page { max-width: 900px; margin: 0 auto; padding: 0 0 48px; }

    /* ── Cover Header (stays dark — forced) ── */
    .cover {
      background: linear-gradient(135deg, #0f0f0f 0%, #1a0000 50%, #0f0f0f 100%);
      border-bottom: 3px solid ${primary};
      padding: 36px 48px 32px;
      position: relative;
      overflow: hidden;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    .cover::before {
      content: '';
      position: absolute;
      top: -40px; right: -40px;
      width: 200px; height: 200px;
      background: radial-gradient(circle, rgba(220,38,38,0.15) 0%, transparent 70%);
      border-radius: 50%;
    }

    .cover-top {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 28px;
    }

    .brand { display: flex; align-items: center; gap: 14px; }
    .brand-ghost { flex-shrink: 0; }
    .brand-text-stack { display: flex; flex-direction: column; line-height: 1; }
    .brand-name-top { font-size: 20px; font-weight: 800; color: #f5f5f5; letter-spacing: 0.12em; }
    .brand-name-bottom { font-size: 13px; font-weight: 600; color: ${primary}; letter-spacing: 0.2em; }

    .report-meta { text-align: right; color: #b0b0b0; font-size: 11px; line-height: 1.7; }
    .report-meta strong { color: #e5e5e5; }

    .hunt-title { font-size: 22px; font-weight: 700; color: #f5f5f5; line-height: 1.3; margin-bottom: 16px; }

    .cover-badges { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }

    .sev-badge {
      display: inline-flex; align-items: center; gap: 5px;
      padding: 4px 12px; border-radius: 999px;
      font-size: 11px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase;
      background: ${sevBg}; color: ${sevColor}; border: 1px solid ${sevColor}66;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .sev-dot {
      width: 7px; height: 7px; border-radius: 50%;
      background: ${sevColor};
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }

    .pill { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 10px; font-weight: 600; letter-spacing: 0.04em; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .pill-blue   { background: rgba(56,189,248,0.15); color: #0ea5e9; border: 1px solid rgba(56,189,248,0.4); }
    .pill-purple { background: rgba(139,92,246,0.12); color: #7c3aed; border: 1px solid rgba(139,92,246,0.35); }
    .pill-red    { background: rgba(220,38,38,0.12); color: #dc2626; border: 1px solid rgba(220,38,38,0.4); }

    /* ── Metrics strip (stays dark — forced) ── */
    .metrics {
      display: grid; grid-template-columns: repeat(5, 1fr);
      gap: 1px; background: #333;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .metric {
      background: #1a1a1a; padding: 14px 16px; text-align: center;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .metric-value { font-size: 18px; font-weight: 700; color: ${primary}; line-height: 1; }
    .metric-label { font-size: 10px; color: #c0c0c0; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.06em; }

    /* ── Body (white background, dark text) ── */
    .body { padding: 0 48px; background: #ffffff; }

    .section { margin-top: 28px; }

    .section-title {
      font-size: 11px; font-weight: 700; color: ${primary};
      letter-spacing: 0.12em; text-transform: uppercase;
      margin-bottom: 12px; padding-bottom: 6px;
      border-bottom: 1px solid #e5e7eb;
    }

    /* ── Callout boxes ── */
    .callout { padding: 14px 16px; border-radius: 6px; margin-bottom: 6px; }
    .callout-info    { background: #eff6ff; border-left: 3px solid #3b82f6; }
    .callout-warning { background: #fffbeb; border-left: 3px solid #f59e0b; }
    .callout-danger  { background: #fef2f2; border-left: 3px solid #ef4444; }
    .callout-label { font-size: 10px; font-weight: 700; color: #6b7280; letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 4px; }
    .callout p { color: #1f2937; font-size: 12.5px; line-height: 1.65; }

    /* ── Steps ── */
    .step { display: flex; align-items: flex-start; gap: 12px; padding: 10px 0; border-bottom: 1px solid #f3f4f6; }
    .step:last-child { border-bottom: none; }
    .step-num {
      min-width: 26px; height: 26px; border-radius: 50%;
      background: #fef2f2; border: 1.5px solid ${accent}80;
      color: ${primary}; font-size: 11px; font-weight: 700;
      display: flex; align-items: center; justify-content: center;
      flex-shrink: 0; margin-top: 1px;
    }
    .step-text { color: #1f2937; font-size: 12.5px; line-height: 1.6; }

    /* ── Queries ── */
    .query-block { margin-bottom: 16px; }
    .query-header { display: flex; align-items: center; gap: 6px; margin-bottom: 6px; }
    .code {
      background: #1e1e2e; border: 1px solid #334155; border-radius: 6px;
      padding: 14px 16px; font-family: 'Consolas', 'Monaco', monospace;
      font-size: 11.5px; color: #7dd3fc; white-space: pre-wrap; word-break: break-all;
      line-height: 1.6; -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }

    /* ── MITRE tags ── */
    .mitre-tag {
      display: inline-block; background: #fef2f2; border: 1px solid ${accent}80;
      color: ${primary}; font-size: 11px; font-weight: 600;
      padding: 3px 9px; border-radius: 4px; margin: 2px; font-family: monospace;
    }

    /* ── Lists ── */
    ul { padding-left: 20px; }
    li { color: #1f2937; font-size: 12.5px; margin-bottom: 5px; line-height: 1.6; }

    /* ── Actors ── */
    .actors { display: flex; flex-wrap: wrap; gap: 10px; }
    .actor { display: flex; align-items: center; gap: 10px; background: #f9fafb; border: 1px solid #e5e7eb; padding: 8px 12px; border-radius: 6px; min-width: 180px; }
    .actor-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
    .actor-name { font-size: 12px; font-weight: 600; color: #111827; }
    .actor-meta { font-size: 10px; color: #6b7280; margin-top: 1px; }

    /* ── Two-col grid ── */
    .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; }

    /* ── Footer ── */
    .pdf-footer {
      margin-top: 40px; padding: 16px 48px;
      border-top: 2px solid ${primary};
      display: flex; align-items: center; justify-content: space-between;
      color: #9ca3af; font-size: 10px; background: #f9fafb;
    }
    .pdf-footer-brand { display: flex; align-items: center; gap: 8px; }
    .footer-ghost { opacity: 0.5; }

    /* ── Print button ── */
    .print-btn {
      position: fixed; bottom: 24px; right: 24px;
      background: ${primary}; color: white; border: none; border-radius: 8px;
      padding: 12px 24px; font-size: 14px; font-weight: 600;
      cursor: pointer; box-shadow: 0 4px 20px ${primary}66;
    }
    .print-btn:hover { opacity: 0.88; }
  </style>
</head>
<body>
<div class="page">

  <!-- Cover Header -->
  <div class="cover">
    <div class="cover-top">
      <div class="brand">
        ${logoUrl
          ? `<img src="${escapeHtml(logoUrl)}" alt="logo" style="height:44px;object-fit:contain;background:#fff;padding:4px;border-radius:6px;"/>`
          : `<div class="brand-ghost">${GHOST_SVG}</div>`
        }
        <div class="brand-text-stack">
          <span class="brand-name-top">${coName ? escapeHtml(coName.toUpperCase()) : 'PHANTOM'}</span>
          <span class="brand-name-bottom">${coName ? 'THREAT HUNT REPORT' : 'HUNTER'}</span>
        </div>
      </div>
      <div class="report-meta">
        ${classification ? `<div><strong style="color:${primary};letter-spacing:0.08em;">${escapeHtml(classification)}</strong></div>` : ''}
        <div><strong>Threat Hunt Report</strong></div>
        <div>Generated: ${now}</div>
        ${analystName ? `<div>Analyst: <strong>${escapeHtml(analystName)}</strong></div>` : ''}
        <div>Hunt ID: ${escapeHtml(hunt.id || 'N/A')}</div>
      </div>
    </div>

    <h1 class="hunt-title">${escapeHtml(reportTitle)}</h1>

    <div class="cover-badges">
      <span class="sev-badge">
        <span class="sev-dot"></span>
        ${(sev).charAt(0).toUpperCase() + sev.slice(1)} Severity
      </span>
      ${hunt.category ? `<span class="pill pill-blue">${escapeHtml(hunt.category)}</span>` : ''}
      ${hunt.difficulty ? `<span class="pill pill-purple">${escapeHtml(hunt.difficulty)}</span>` : ''}
      ${(hunt.mitreTechniques || []).slice(0, 3).map(t => {
        const id = typeof t === 'string' ? t : (t?.id || '');
        return `<span class="pill pill-red">${escapeHtml(id)}</span>`;
      }).join('')}
      ${(hunt.mitreTechniques || []).length > 3 ? `<span class="pill pill-red">+${(hunt.mitreTechniques || []).length - 3} more</span>` : ''}
    </div>
  </div>

  <!-- Metrics Strip -->
  <div class="metrics">
    <div class="metric">
      <div class="metric-value">${hunt.relevanceScore || 0}%</div>
      <div class="metric-label">Relevance</div>
    </div>
    <div class="metric">
      <div class="metric-value">${hunt.confidence || 0}%</div>
      <div class="metric-label">Confidence</div>
    </div>
    <div class="metric">
      <div class="metric-value">${hunt.dataSourceCoverage || 0}%</div>
      <div class="metric-label">Coverage</div>
    </div>
    <div class="metric">
      <div class="metric-value">${escapeHtml(hunt.estimatedHuntTime || hunt.estimatedTime || 'N/A')}</div>
      <div class="metric-label">Est. Time</div>
    </div>
    <div class="metric">
      <div class="metric-value">${escapeHtml(hunt.frequency || 'Weekly')}</div>
      <div class="metric-label">Frequency</div>
    </div>
  </div>

  <!-- Body -->
  <div class="body">

    <!-- Why Relevant -->
    ${sections.overview !== false ? `
    <div class="section">
      <div class="callout callout-info">
        <div class="callout-label">Why This Hunt Matters</div>
        <p>${escapeHtml(hunt.whyRelevant || '')}</p>
      </div>
    </div>

    <!-- Threat Context -->
    ${hunt.threatContext ? `
    <div class="section">
      <div class="callout callout-danger">
        <div class="callout-label">Threat Intelligence Context</div>
        <p>${escapeHtml(hunt.threatContext)}</p>
      </div>
    </div>` : ''}

    <!-- Hypothesis -->
    <div class="section">
      <div class="section-title">Threat Hypothesis</div>
      <div class="callout callout-warning">
        <p>${escapeHtml(hunt.hypothesis || '')}</p>
      </div>
    </div>

    <!-- Hunt Methodology -->
    ${hunt.huntMethodology ? `
    <div class="section">
      <div class="section-title">Hunt Methodology</div>
      <p style="font-size:12.5px;color:#1f2937;line-height:1.65;">${escapeHtml(hunt.huntMethodology)}</p>
    </div>` : ''}

    <!-- MITRE Techniques -->
    ${(hunt.mitreTechniques || []).length > 0 ? `
    <div class="section">
      <div class="section-title">MITRE ATT&amp;CK Techniques</div>
      <div>${mitre}</div>
    </div>` : ''}

    <!-- Threat Actors -->
    ${(hunt.relevantThreatActors || []).length > 0 ? `
    <div class="section">
      <div class="section-title">Relevant Threat Actors</div>
      <div class="actors">${actors}</div>
    </div>` : ''}` : ''}

    <!-- Hunt Procedure -->
    ${sections.huntSteps !== false ? `
    <div class="section">
      <div class="section-title">Hunt Procedure (${(hunt.huntSteps || []).length} Steps)</div>
      ${steps}
    </div>

    ${hunt.analystTips?.length > 0 ? `
    <div class="section">
      <div class="section-title">Analyst Tips</div>
      <ul>${listItems(hunt.analystTips)}</ul>
    </div>` : ''}

    ${hunt.investigationSteps?.length > 0 ? `
    <div class="section">
      <div class="section-title">When You Find Something — Investigation Steps</div>
      ${investigationSteps}
    </div>` : ''}` : ''}

    <!-- Queries -->
    ${sections.queries !== false && (hunt.exampleQueries || []).length > 0 ? `
    <div class="section">
      <div class="section-title">Example Queries</div>
      ${queries}
    </div>` : ''}

    <!-- IOCs / Behaviors -->
    ${sections.iocs !== false ? `
    ${hunt.whatToLookFor?.length > 0 ? `
    <div class="section">
      <div class="section-title">What to Look For</div>
      <ul>${listItems(hunt.whatToLookFor)}</ul>
    </div>` : ''}

    <div class="section">
      <div class="grid-2">
        <div>
          <div class="section-title">Suspicious Behaviors</div>
          <ul>${listItems(hunt.suspiciousBehaviors)}</ul>
        </div>
        ${(hunt.iocTypes || []).length > 0 ? `
        <div>
          <div class="section-title">IOC Types to Collect</div>
          <ul>${listItems(hunt.iocTypes)}</ul>
        </div>` : (hunt.truePositiveIndicators || []).length > 0 ? `
        <div>
          <div class="section-title">True Positive Indicators</div>
          <ul>${listItems(hunt.truePositiveIndicators)}</ul>
        </div>` : '<div></div>'}
      </div>
    </div>

    ${(() => { const fp = [...(hunt.falsePositives || []), ...(hunt.falsePositiveIndicators || [])]; return fp.length > 0 ? `
    <div class="section">
      <div class="section-title">False Positive Reduction</div>
      <ul>${listItems(fp)}</ul>
    </div>` : ''; })()}

    ${hunt.triageGuidance ? `
    <div class="section">
      <div class="section-title">Triage Guidance</div>
      <div class="callout callout-danger">
        <p>${escapeHtml(hunt.triageGuidance)}</p>
      </div>
    </div>` : ''}

    ${(hunt.escalationRecommendations || []).length > 0 ? `
    <div class="section">
      <div class="section-title">Escalation Recommendations</div>
      <ul>${listItems(hunt.escalationRecommendations)}</ul>
    </div>` : ''}` : ''}

    <!-- Remediation + Detection Opportunity -->
    ${sections.remediation !== false ? `
    ${(hunt.remediationActions || []).length > 0 ? `
    <div class="section">
      <div class="section-title">Remediation Actions</div>
      <ul>${listItems(hunt.remediationActions)}</ul>
    </div>` : ''}
    ${hunt.detectionOpportunity ? `
    <div class="section">
      <div class="callout callout-info">
        <div class="callout-label">Detection Opportunity</div>
        <p>${escapeHtml(hunt.detectionOpportunity)}</p>
      </div>
    </div>` : ''}` : ''}

    <!-- Data Sources -->
    ${(hunt.dataSources || []).length > 0 ? `
    <div class="section">
      <div class="section-title">Required Data Sources</div>
      <ul>${listItems(hunt.dataSources)}</ul>
    </div>` : ''}

  </div>

  <!-- Footer -->
  <div class="pdf-footer">
    <div class="pdf-footer-brand">
      ${logoUrl
        ? `<img src="${escapeHtml(logoUrl)}" alt="logo" style="height:18px;object-fit:contain;opacity:0.6;"/>`
        : `<span class="footer-ghost">${GHOST_SVG.replace('width="48"', 'width="22"').replace('height="56"', 'height="26"')}</span>`
      }
      <span>${coName ? escapeHtml(coName) + ' &mdash; ' : ''}Phantom Hunter v1.0</span>
    </div>
    <div style="text-align:right;">
      ${footerNote ? `<div style="margin-bottom:2px;font-style:italic;">${escapeHtml(footerNote)}</div>` : ''}
      <span>Hunt generated ${genDate} &nbsp;&bull;&nbsp; ${escapeHtml(hunt.id || '')}</span>
    </div>
  </div>

</div>

<button class="print-btn no-print" onclick="window.print()">
  ⬇ Download PDF
</button>

</body>
</html>`;
}

// ── Multi-Hunt PDF ─────────────────────────────────────────────────────────────

function buildPrintableHTML(hunts, profile) {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Phantom Hunter — ${escapeHtml(profile?.companyName || 'Hunt Report')}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', Arial, sans-serif; background: #ffffff; color: #111827; font-size: 13px; line-height: 1.6; }
    @page { size: A4; margin: 0; }
    @media print {
      .no-print { display: none; }
      .hunt-card { page-break-inside: avoid; }
      .cover, .stats-row, .stat, .hunt-card-header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
    .page { max-width: 900px; margin: 0 auto; padding: 0 0 48px; }
    .cover {
      background: linear-gradient(135deg, #0f0f0f 0%, #1a0000 50%, #0f0f0f 100%);
      border-bottom: 3px solid #dc2626; padding: 40px 48px;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .brand { display: flex; align-items: center; gap: 14px; margin-bottom: 28px; }
    .brand-name-top { font-size: 20px; font-weight: 800; color: #f5f5f5; letter-spacing: 0.12em; display: block; }
    .brand-name-bottom { font-size: 13px; font-weight: 600; color: #dc2626; letter-spacing: 0.2em; display: block; }
    .report-title { font-size: 26px; font-weight: 700; color: #f5f5f5; margin-bottom: 8px; }
    .report-sub { color: #d0d0d0; font-size: 13px; }
    .report-sub strong { color: #ffffff; }
    .stats-row { display: flex; gap: 1px; background: #333; margin-top: 28px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .stat { flex: 1; background: #1a1a1a; padding: 14px; text-align: center; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .stat-val { font-size: 22px; font-weight: 700; color: #dc2626; }
    .stat-lbl { font-size: 10px; color: #c0c0c0; text-transform: uppercase; letter-spacing: 0.06em; margin-top: 3px; }
    .body { padding: 0 48px; background: #ffffff; }
    .hunt-card { margin-top: 28px; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
    .hunt-card-header { background: #1a1a1a; padding: 16px 20px; border-bottom: 1px solid #333; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .hunt-card-num { font-size: 10px; color: #a0a0a0; font-weight: 600; letter-spacing: 0.08em; text-transform: uppercase; margin-bottom: 4px; }
    .hunt-card-title { font-size: 15px; font-weight: 700; color: #f5f5f5; margin-bottom: 8px; }
    .hunt-card-badges { display: flex; gap: 6px; flex-wrap: wrap; }
    .sev-badge { display: inline-flex; align-items: center; gap: 5px; padding: 3px 10px; border-radius: 999px; font-size: 10px; font-weight: 700; letter-spacing: 0.06em; text-transform: uppercase; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .pill { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 10px; font-weight: 600; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .pill-blue   { background: #eff6ff; color: #1d4ed8; border: 1px solid #bfdbfe; }
    .pill-purple { background: #f5f3ff; color: #6d28d9; border: 1px solid #ddd6fe; }
    .pill-red    { background: #fef2f2; color: #dc2626; border: 1px solid #fca5a5; }
    .hunt-card-body { padding: 16px 20px; background: #ffffff; }
    .hunt-meta { display: flex; gap: 20px; margin-bottom: 12px; }
    .hunt-meta-item { font-size: 11px; color: #6b7280; }
    .hunt-meta-item strong { color: #dc2626; font-size: 13px; }
    p { color: #1f2937; font-size: 12.5px; line-height: 1.65; margin-bottom: 8px; }
    .steps-list { padding-left: 0; list-style: none; }
    .steps-list li { display: flex; gap: 10px; align-items: flex-start; padding: 6px 0; border-bottom: 1px solid #f3f4f6; font-size: 12px; color: #1f2937; }
    .step-n { min-width: 20px; height: 20px; border-radius: 50%; background: #fef2f2; border: 1.5px solid #fca5a5; color: #dc2626; font-size: 10px; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
    .mitre-tag { display: inline-block; background: #fef2f2; border: 1px solid #fca5a5; color: #dc2626; font-size: 10px; font-weight: 600; padding: 2px 7px; border-radius: 4px; margin: 2px; font-family: monospace; }
    .section-label { font-size: 10px; font-weight: 700; color: #6b7280; letter-spacing: 0.1em; text-transform: uppercase; margin: 12px 0 6px; }
    .pdf-footer { margin-top: 40px; padding: 16px 48px; border-top: 2px solid #dc2626; display: flex; align-items: center; justify-content: space-between; color: #9ca3af; font-size: 10px; background: #f9fafb; }
    .print-btn { position: fixed; bottom: 24px; right: 24px; background: #dc2626; color: white; border: none; border-radius: 8px; padding: 12px 24px; font-size: 14px; font-weight: 600; cursor: pointer; }
  </style>
</head>
<body>
<div class="page">
  <div class="cover">
    <div class="brand">
      ${GHOST_SVG}
      <div>
        <span class="brand-name-top">PHANTOM</span>
        <span class="brand-name-bottom">HUNTER</span>
      </div>
    </div>
    <div class="report-title">Threat Hunt Report</div>
    <div class="report-sub">
      <strong>${escapeHtml(profile?.companyName || 'N/A')}</strong> &nbsp;&bull;&nbsp;
      ${escapeHtml(profile?.industry || 'N/A')} &nbsp;&bull;&nbsp;
      Generated ${now}
    </div>
    <div class="stats-row">
      <div class="stat"><div class="stat-val">${hunts.length}</div><div class="stat-lbl">Total Hunts</div></div>
      <div class="stat"><div class="stat-val">${hunts.filter(h => h.severity === 'critical').length}</div><div class="stat-lbl">Critical</div></div>
      <div class="stat"><div class="stat-val">${hunts.filter(h => h.severity === 'high').length}</div><div class="stat-lbl">High</div></div>
      <div class="stat"><div class="stat-val">${hunts.reduce((s, h) => s + (h.mitreTechniques?.length || 0), 0)}</div><div class="stat-lbl">MITRE Techniques</div></div>
    </div>
  </div>

  <div class="body">
    ${hunts.map((hunt, idx) => {
      const sev = hunt.severity || 'medium';
      const sc = severityColor(sev);
      const sb = severityBg(sev);
      return `
    <div class="hunt-card">
      <div class="hunt-card-header">
        <div class="hunt-card-num">Hunt ${String(idx + 1).padStart(2, '0')} of ${hunts.length}</div>
        <div class="hunt-card-title">${escapeHtml(hunt.title)}</div>
        <div class="hunt-card-badges">
          <span class="sev-badge" style="background:${sb};color:${sc};border:1.5px solid ${sc};">${sev.toUpperCase()}</span>
          ${hunt.category ? `<span class="pill pill-blue">${escapeHtml(hunt.category)}</span>` : ''}
          ${(hunt.mitreTechniques || []).slice(0, 4).map(t => `<span class="mitre-tag">${escapeHtml(t)}</span>`).join('')}
        </div>
      </div>
      <div class="hunt-card-body">
        <div class="hunt-meta">
          <div class="hunt-meta-item"><strong>${hunt.relevanceScore || 0}%</strong><br>Relevance</div>
          <div class="hunt-meta-item"><strong>${hunt.confidence || 0}%</strong><br>Confidence</div>
          <div class="hunt-meta-item"><strong>${escapeHtml(hunt.estimatedTime || 'N/A')}</strong><br>Est. Time</div>
          <div class="hunt-meta-item"><strong>${escapeHtml(hunt.difficulty || 'N/A')}</strong><br>Difficulty</div>
        </div>
        <p>${escapeHtml(hunt.whyRelevant || '')}</p>
        ${(hunt.huntSteps || []).length > 0 ? `
        <div class="section-label">Hunt Steps</div>
        <ul class="steps-list">
          ${(hunt.huntSteps || []).slice(0, 5).map((s, i) => `<li><span class="step-n">${i + 1}</span><span>${escapeHtml(s)}</span></li>`).join('')}
          ${(hunt.huntSteps || []).length > 5 ? `<li style="color:#909090;font-size:11px;padding:6px 0">+ ${hunt.huntSteps.length - 5} more steps...</li>` : ''}
        </ul>` : ''}
        ${hunt.triageGuidance ? `
        <div class="section-label">Triage Guidance</div>
        <p>${escapeHtml(hunt.triageGuidance)}</p>` : ''}
      </div>
    </div>`;
    }).join('')}
  </div>

  <div class="pdf-footer">
    <span>Phantom Hunter v1.0 &mdash; Threat Intelligence Platform</span>
    <span>Report generated ${now}</span>
  </div>
</div>

<button class="print-btn no-print" onclick="window.print()">⬇ Download PDF</button>

</body>
</html>`;
}

// ── HTML escape ───────────────────────────────────────────────────────────────

function escapeHtml(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
