/**
 * Export Service
 * Handles exporting hunt results in various formats.
 * PDF export is mocked (requires a library like jsPDF for full implementation).
 */

// ── JSON Export ───────────────────────────────────────────────────────────────

export function exportHuntsAsJSON(hunts, filename = 'threat-hunts') {
  const exportData = {
    exportedAt: new Date().toISOString(),
    generator: 'Threat Hunt Generator v1.0',
    huntCount: hunts.length,
    hunts: hunts.map(h => ({
      id: h.id,
      title: h.title,
      category: h.category,
      severity: h.severity,
      confidence: h.confidence,
      relevanceScore: h.relevanceScore,
      mitreTechniques: h.mitreTechniques,
      hypothesis: h.hypothesis,
      whyRelevant: h.whyRelevant,
      huntSteps: h.huntSteps,
      exampleQueries: h.exampleQueries,
      dataSources: h.dataSources,
      suspiciousBehaviors: h.suspiciousBehaviors,
      truePositiveIndicators: h.truePositiveIndicators,
      falsePositiveIndicators: h.falsePositiveIndicators,
      triageGuidance: h.triageGuidance,
      remediationActions: h.remediationActions,
      tags: h.tags,
      generatedAt: h.generatedAt,
    })),
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `${filename}-${formatDate()}.json`);
  URL.revokeObjectURL(url);
}

// ── Single Hunt JSON ──────────────────────────────────────────────────────────

export function exportSingleHuntJSON(hunt) {
  const blob = new Blob([JSON.stringify(hunt, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `hunt-${hunt.id}-${formatDate()}.json`);
  URL.revokeObjectURL(url);
}

// ── Markdown Export ───────────────────────────────────────────────────────────

export function exportHuntAsMarkdown(hunt) {
  const lines = [
    `# ${hunt.title}`,
    '',
    `**Category:** ${hunt.category}  `,
    `**Severity:** ${hunt.severity}  `,
    `**Confidence:** ${hunt.confidence}%  `,
    `**Estimated Time:** ${hunt.estimatedTime}  `,
    `**Difficulty:** ${hunt.difficulty}  `,
    '',
    '## Why This Hunt is Relevant',
    hunt.whyRelevant || '',
    '',
    '## Threat Hypothesis',
    hunt.hypothesis || '',
    '',
    '## MITRE ATT&CK Techniques',
    (hunt.mitreTechniques || []).map(t => `- \`${t}\``).join('\n'),
    '',
    '## Required Data Sources',
    (hunt.dataSources || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Hunt Procedure',
    (hunt.huntSteps || []).map((s, i) => `${i + 1}. ${s}`).join('\n'),
    '',
    '## Example Queries',
    ...(hunt.exampleQueries || []).flatMap(q => [
      `### ${q.platform}`,
      '```',
      q.query,
      '```',
      '',
    ]),
    '## Suspicious Behaviors to Look For',
    (hunt.suspiciousBehaviors || []).map(s => `- ${s}`).join('\n'),
    '',
    '## True Positive Indicators',
    (hunt.truePositiveIndicators || []).map(s => `- ${s}`).join('\n'),
    '',
    '## False Positive Indicators',
    (hunt.falsePositiveIndicators || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Triage Guidance',
    hunt.triageGuidance || '',
    '',
    '## Escalation Recommendations',
    (hunt.escalationRecommendations || []).map(s => `- ${s}`).join('\n'),
    '',
    '## Remediation Actions',
    (hunt.remediationActions || []).map(s => `- ${s}`).join('\n'),
    '',
    `---`,
    `*Generated by Threat Hunt Generator on ${new Date(hunt.generatedAt || Date.now()).toLocaleDateString()}*`,
  ];

  const md = lines.join('\n');
  const blob = new Blob([md], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `hunt-${sanitizeFilename(hunt.title)}-${formatDate()}.md`);
  URL.revokeObjectURL(url);
}

// ── Copy to Clipboard ─────────────────────────────────────────────────────────

export async function copyHuntToClipboard(hunt) {
  const text = formatHuntAsText(hunt);
  await navigator.clipboard.writeText(text);
}

export async function copyQueryToClipboard(query) {
  await navigator.clipboard.writeText(query.query);
}

// ── PDF Export (mocked) ───────────────────────────────────────────────────────

export function exportHuntsAsPDF(hunts, companyProfile) {
  // In a full implementation, use jsPDF or react-pdf to generate a real PDF.
  // For now, we show a "print" dialog with styled HTML.
  const html = buildPrintableHTML(hunts, companyProfile);
  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 500);
  }
}

// ── CSV Export ─────────────────────────────────────────────────────────────────

export function exportHuntsAsCSV(hunts, filename = 'threat-hunts') {
  const headers = [
    'ID', 'Title', 'Category', 'Severity', 'Confidence', 'Relevance Score',
    'Difficulty', 'Estimated Time', 'MITRE Techniques', 'Tags',
  ];

  const rows = hunts.map(h => [
    h.id,
    `"${(h.title || '').replace(/"/g, '""')}"`,
    h.category,
    h.severity,
    h.confidence,
    h.relevanceScore,
    h.difficulty,
    h.estimatedTime,
    `"${(h.mitreTechniques || []).join(', ')}"`,
    `"${(h.tags || []).join(', ')}"`,
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  triggerDownload(url, `${filename}-${formatDate()}.csv`);
  URL.revokeObjectURL(url);
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function triggerDownload(url, filename) {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
}

function formatDate() {
  return new Date().toISOString().split('T')[0];
}

function sanitizeFilename(str) {
  return (str || 'hunt').replace(/[^a-z0-9]/gi, '-').toLowerCase().slice(0, 40);
}

function formatHuntAsText(hunt) {
  return [
    `THREAT HUNT: ${hunt.title}`,
    `${'='.repeat(60)}`,
    '',
    `Category: ${hunt.category} | Severity: ${hunt.severity} | Confidence: ${hunt.confidence}%`,
    '',
    'WHY RELEVANT',
    hunt.whyRelevant,
    '',
    'HYPOTHESIS',
    hunt.hypothesis,
    '',
    'MITRE TECHNIQUES',
    (hunt.mitreTechniques || []).join(', '),
    '',
    'HUNT STEPS',
    (hunt.huntSteps || []).map((s, i) => `${i + 1}. ${s}`).join('\n'),
    '',
    'SUSPICIOUS BEHAVIORS',
    (hunt.suspiciousBehaviors || []).map(s => `• ${s}`).join('\n'),
    '',
    'TRIAGE GUIDANCE',
    hunt.triageGuidance,
  ].join('\n');
}

function buildPrintableHTML(hunts, profile) {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Threat Hunt Report — ${profile?.companyName || 'Report'}</title>
  <style>
    body { font-family: Arial, sans-serif; color: #1a1a2e; max-width: 900px; margin: 0 auto; padding: 24px; }
    h1 { color: #0f3460; border-bottom: 2px solid #0f3460; padding-bottom: 8px; }
    h2 { color: #16213e; font-size: 1.1em; margin-top: 24px; }
    h3 { color: #0f3460; font-size: 0.95em; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; margin-right: 4px; }
    .critical { background: #fee2e2; color: #dc2626; }
    .high     { background: #ffedd5; color: #ea580c; }
    .medium   { background: #fef9c3; color: #ca8a04; }
    .low      { background: #dcfce7; color: #16a34a; }
    .hunt-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 24px; page-break-inside: avoid; }
    .meta { color: #6b7280; font-size: 13px; margin-bottom: 12px; }
    code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 12px; }
    pre { background: #1e293b; color: #7dd3fc; padding: 16px; border-radius: 8px; font-size: 12px; overflow-x: auto; }
    ul { padding-left: 20px; }
    li { margin-bottom: 4px; font-size: 14px; }
    .report-header { background: #0f3460; color: white; padding: 24px; border-radius: 8px; margin-bottom: 32px; }
    .report-header h1 { color: white; border-color: rgba(255,255,255,0.3); }
    @media print { .hunt-card { page-break-inside: avoid; } }
  </style>
</head>
<body>
  <div class="report-header">
    <h1>Threat Hunt Report</h1>
    <p><strong>Organization:</strong> ${profile?.companyName || 'N/A'} | <strong>Industry:</strong> ${profile?.industry || 'N/A'}</p>
    <p><strong>Generated:</strong> ${new Date().toLocaleDateString()} | <strong>Total Hunts:</strong> ${hunts.length}</p>
  </div>
  ${hunts.map((hunt, idx) => `
  <div class="hunt-card">
    <h2>${idx + 1}. ${hunt.title}</h2>
    <div class="meta">
      <span class="badge ${hunt.severity}">${(hunt.severity || '').toUpperCase()}</span>
      Category: ${hunt.category} &nbsp;|&nbsp; Confidence: ${hunt.confidence}% &nbsp;|&nbsp; Time: ${hunt.estimatedTime}
    </div>
    <h3>Why This Hunt Matters</h3>
    <p>${hunt.whyRelevant || ''}</p>
    <h3>Hypothesis</h3>
    <p>${hunt.hypothesis || ''}</p>
    <h3>MITRE ATT&CK Techniques</h3>
    <p>${(hunt.mitreTechniques || []).map(t => `<code>${t}</code>`).join(' ')}</p>
    <h3>Hunt Steps</h3>
    <ol>${(hunt.huntSteps || []).map(s => `<li>${s}</li>`).join('')}</ol>
    ${hunt.exampleQueries?.length ? `
    <h3>Example Query (${hunt.exampleQueries[0].platform})</h3>
    <pre>${hunt.exampleQueries[0].query}</pre>` : ''}
    <h3>Suspicious Behaviors</h3>
    <ul>${(hunt.suspiciousBehaviors || []).map(s => `<li>${s}</li>`).join('')}</ul>
    <h3>Triage Guidance</h3>
    <p>${hunt.triageGuidance || ''}</p>
  </div>`).join('')}
</body>
</html>`;
}
